// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ServiceClients.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class InlineResponse200
    {
        /// <summary>
        /// Initializes a new instance of the InlineResponse200 class.
        /// </summary>
        public InlineResponse200() { }

        /// <summary>
        /// Initializes a new instance of the InlineResponse200 class.
        /// </summary>
        public InlineResponse200(string deviceId = default(string), DateTime? timestamp = default(DateTime?), double? value = default(double?))
        {
            DeviceId = deviceId;
            Timestamp = timestamp;
            Value = value;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceId")]
        public string DeviceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; set; }

    }
}
